### ISSUE TITLE
📝 Documentation:  Missing Examples in Documentation

### ISSUE THREAD

**Issue by yashsharma999** [JoshuaKGoldberg/are-docs-informative#30]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/are-docs-informative/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Hi there,

While going through the README, I noticed that some parts of it lack examples, making it difficult to understand the project . Adding a simple jsDoc example might be helpful . 

Something like : 
```ts
/**
 * Calculates the sum of two numbers.
 *
 * @param {number} a - The first number to be added.
 * @param {number} b - The second number to be added.
 * @returns {number} The sum of the two numbers.
 *
 * @example
 * // returns 5
 * sum(2, 3);
 */
const sum = (a: number, b: number) => {
	return a + b;
};

areDocsInformative("Calculates the sum of two numbers.", "sum"); // true
```

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for filing! I appreciate the general idea - but there already are examples, no? #23.  At the top of the file...

> ```ts
> import { areDocsInformative } from "are-docs-informative";
> 
> areDocsInformative("The user id.", "userId"); // false
> areDocsInformative("Retrieved user id.", "userId"); // true
> ```

...as well as specific examples from each 

From your code block it looks like you're using https://github.com/gajus/eslint-plugin-jsdoc/tree/b23a58799816ddbd0f64780467c37432374d6ab0#user-content-eslint-plugin-jsdoc-rules-informative-docs. Perhaps this issue would be better filed there?

Was there anything specific to _this_ package you'd want documented?

**Comment by yashsharma999** [comment]
So you are saying my issue is related to a particular use-case of your code and not related to _this_ package as such , hence it would be better to file it in the specific repo , as you mentioned ? 

P.S. I am just new to open-source 😅

**Comment by JoshuaKGoldberg** [comment]
Yup that's exactly what I'm saying. This library is used by [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc). That's the place you want the docs I think.

Welcome to open source! 🤗 I hope you're enjoying it so far!

Closing this issue for now, but feel free to post back if there's something specific to this package that should be documented. Cheers! ♥️
